<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>bea39236-3bf2-4688-aa54-064e19615f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='webmail']/div/div/div/main/div[2]/div/div/div/div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>882c98c5-e8f7-4b17-b590-e8666ea0ecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>8b2f100d-52c3-4302-aba2-75123cbe94f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webmail&quot;)/div[@class=&quot;webmailctn&quot;]/div[@class=&quot;webmaillogo&quot;]/div[@class=&quot;ymain&quot;]/main[1]/div[@class=&quot;wmmain&quot;]/div[@class=&quot;wmleft&quot;]/div[@class=&quot;wminbox&quot;]/div[@class=&quot;wminboxheader&quot;]/div[6]</value>
      <webElementGuid>544d3525-1d7f-4b82-9dff-f24ed69476da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='webmail']/div/div/div/main/div[2]/div/div/div/div[6]</value>
      <webElementGuid>b96c9a33-81d3-461a-8747-49861d097b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/following::div[3]</value>
      <webElementGuid>81a9a690-cb98-4cc1-a3c1-80da0c4373b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::div[4]</value>
      <webElementGuid>464e716b-1c4a-4531-acf4-7876dfdedbf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[2]/preceding::div[2]</value>
      <webElementGuid>c6b08749-d683-423f-b963-61a492ee863b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div/div/div/div[6]</value>
      <webElementGuid>d700186f-a143-4b48-b6a4-d836b18a4d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '' or . = '')]</value>
      <webElementGuid>83e987da-cf15-4c2e-84c2-c60f5cb4a9e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
