<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_374896</name>
   <tag></tag>
   <elementGuidId>a8fc6b90-a83d-4c58-a9a6-288ee8e36df2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/table/tbody/tr[2]/td/div/div[2]/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>281e83ba-af9e-4d42-82f5-022d0abcbb3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>374896</value>
      <webElementGuid>0885fa73-7802-4b88-8724-30058c03892f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[2]/p[3]</value>
      <webElementGuid>78593631-5b22-433a-9ba0-77273f293208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail</value>
      <webElementGuid>77cbd05e-2dd5-4421-a82e-c3f7d1639d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/table/tbody/tr[2]/td/div/div[2]/p[3]</value>
      <webElementGuid>cedd3d74-b228-49f1-af4b-410038cf2468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time Password'])[1]/following::p[3]</value>
      <webElementGuid>d21e610b-d0e3-4f20-a588-527a31e19d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::p[3]</value>
      <webElementGuid>114a986d-d3a5-4373-b6fb-9b52c2cf24b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mail', '&quot;', ')/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[2]/p[3]')])[1]/preceding::p[8]</value>
      <webElementGuid>9525a5c7-ee16-4d53-a6af-9f73c7831b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='374896']/parent::*</value>
      <webElementGuid>f27411b4-0b85-40ef-a145-666d83d7e735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>212412d3-b1e8-47d5-8654-0fed23516e7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '374896' or . = '374896')]</value>
      <webElementGuid>ca4f6893-26b3-49a8-b202-649385fca12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
