<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_651037</name>
   <tag></tag>
   <elementGuidId>13acc71e-3384-4d17-bf88-cb46db19d3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mail']/div/table/tbody/tr[2]/td/div/div[2]/p[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0275de4c-85d0-4006-bb97-513ee2405670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>651037</value>
      <webElementGuid>043a5ecc-200a-4125-9eda-170c6818c8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mail&quot;)/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[2]/p[3]</value>
      <webElementGuid>70a0e72f-65a9-4619-8b31-00ff9e3196bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifmail_1</value>
      <webElementGuid>9c430129-6bf3-4666-9443-42ffa7cbd578</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mail']/div/table/tbody/tr[2]/td/div/div[2]/p[3]</value>
      <webElementGuid>7ce0539d-5da7-41de-a020-8a7f5d4051c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='One-time Password'])[1]/following::p[3]</value>
      <webElementGuid>7c7526ba-8b89-4b1a-98d4-3975750adcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=''])[1]/following::p[3]</value>
      <webElementGuid>b671feb1-c57b-460c-8c56-34675a7b12eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mail', '&quot;', ')/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[2]/p[3]')])[1]/preceding::p[8]</value>
      <webElementGuid>c7f508bf-7f6e-4ed5-bb2d-53ca15243e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='651037']/parent::*</value>
      <webElementGuid>6b09f300-6502-46ed-88a1-73e2d39c6488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>3177a382-ad00-4aeb-9c71-540ef9c05e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '651037' or . = '651037')]</value>
      <webElementGuid>f9f02765-eaba-45b0-ae1d-e69f650f58a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
