<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Approved</name>
   <tag></tag>
   <elementGuidId>2773fc46-fe82-4a90-9dc8-c3490d7116b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uncontrolled-tab-example-tab-approved']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uncontrolled-tab-example-tab-approved</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8788d38-10f5-4534-92bb-4c40d1c0027b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tab-approved</value>
      <webElementGuid>8119c788-b88f-4fce-80cd-d94de95ae402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>ab7cfd94-0548-4395-a314-dcfa982c58e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>67389c37-6214-413b-81c4-a0c50a545e85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>approved</value>
      <webElementGuid>d748ddb6-9094-406c-833e-b75a5d88edaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tabpane-approved</value>
      <webElementGuid>65f47317-5f52-41a4-b8a9-fe58d71370e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c4f25856-92db-4bd4-a5ec-c001bf5f0d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>35c35e42-a9f7-4fc1-8e6f-0cb29c9903f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approved</value>
      <webElementGuid>889f51cb-6e94-473a-a901-5ff0b934b9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tab-approved&quot;)</value>
      <webElementGuid>debd05c6-5d1f-42ad-9f16-3407288072ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uncontrolled-tab-example-tab-approved']</value>
      <webElementGuid>4b51b5d9-d865-4b68-820e-689789bc4b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/section/div/section/div/nav/a[3]</value>
      <webElementGuid>d8ec2fc9-dcd2-40fd-8fd2-94f6544cb23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Approved')]</value>
      <webElementGuid>85358807-ad20-4423-8469-859da19ba1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create New'])[1]/following::a[3]</value>
      <webElementGuid>8dd6b24d-f157-4de7-9021-da519843eb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Your Identifications'])[1]/following::a[3]</value>
      <webElementGuid>f7af7136-c658-45d8-8b1a-bac432bb5d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sender/Device ID'])[1]/preceding::a[2]</value>
      <webElementGuid>3bc7c03e-ede6-4d45-b7dc-fb761512d260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::a[2]</value>
      <webElementGuid>f70c7cdb-4f00-4435-befd-3d5e5409970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Approved']/parent::*</value>
      <webElementGuid>14503d1f-82da-4409-9a0e-7bd5f0d7f321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>ea857c6a-bfaa-4aad-ba13-900d098e12eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>311731aa-80c1-4941-85b3-dbc10bbb9c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uncontrolled-tab-example-tab-approved' and @href = '#' and (text() = 'Approved' or . = 'Approved')]</value>
      <webElementGuid>a5fb2b11-ce2a-412e-91e9-f2f451354d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
