<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ungrouped</name>
   <tag></tag>
   <elementGuidId>f973a41c-0465-4623-89f3-e5118757d515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uncontrolled-tab-example-tab-ungrouped</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uncontrolled-tab-example-tab-ungrouped']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Ungrouped&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>860bc3d8-2ef4-4140-ba66-1bc75053d392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tab-ungrouped</value>
      <webElementGuid>7113964e-d926-45f7-a4b4-ea4db03dc4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>585f818e-62a5-42e6-bad9-4b3aa13f3940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>3ad3008e-2991-4648-bed1-d26ed25a12ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>ungrouped</value>
      <webElementGuid>e2538e5d-fd73-4084-a74b-5b0754682dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>uncontrolled-tab-example-tabpane-ungrouped</value>
      <webElementGuid>55284ab8-7e2b-408d-bff7-20ae02ddb9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>75b4d57a-42a3-40ad-be00-0f5f4ed0a706</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-item nav-link</value>
      <webElementGuid>5eed465b-65f1-4d69-a197-d4ae48fd32a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ungrouped</value>
      <webElementGuid>1246f1d4-cad6-4bf5-bdf4-92fb40d57114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tab-ungrouped&quot;)</value>
      <webElementGuid>705caaf5-e1f6-4400-9259-1dabfbfa50bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uncontrolled-tab-example-tab-ungrouped']</value>
      <webElementGuid>34d468b3-0fd9-41a9-8fae-7cd665f25494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/section/div/div[2]/nav/a[2]</value>
      <webElementGuid>045a111f-52a5-49f7-9b4e-b34918991f1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ungrouped')]</value>
      <webElementGuid>6b9a0abf-2e10-436a-bff2-a4d7f8fdee1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Grouped Contacts'])[1]/following::a[2]</value>
      <webElementGuid>4a1d0d0b-bb18-4b20-84ea-25b01a4c8e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add, Edit or Delete Contacts'])[1]/following::a[2]</value>
      <webElementGuid>9fefe0fd-9313-4fa0-8ca6-2dafd7867b5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::a[1]</value>
      <webElementGuid>73674dfb-d6bb-4fb5-b349-a6d013ca82c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/preceding::a[1]</value>
      <webElementGuid>a43a0575-2119-42bf-8cd7-f90ab2d7ea17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ungrouped']/parent::*</value>
      <webElementGuid>5a0d73ad-4a91-44fa-8b96-a8567733fdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>06e481ce-013e-4d15-a051-6e7f095b93ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a[2]</value>
      <webElementGuid>f7d0f31d-12cc-487c-9e0c-c35e80a20b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uncontrolled-tab-example-tab-ungrouped' and @href = '#' and (text() = 'Ungrouped' or . = 'Ungrouped')]</value>
      <webElementGuid>727ffefc-0f7b-4277-845d-dcedc4e7455e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
