<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Service</name>
   <tag></tag>
   <elementGuidId>9742b2ba-ec52-411e-b00f-65f588cec6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.activity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uncontrolled-tab-example-tabpane-grouped']/div/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Service&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dfee196f-b424-4fa4-aa4b-a5a60cf9db73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>activity</value>
      <webElementGuid>f4d833a3-54e1-4362-99d8-d3c1204ee718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Service</value>
      <webElementGuid>c4cf26d6-3710-4532-89e8-c40d70792680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uncontrolled-tab-example-tabpane-grouped&quot;)/div[@class=&quot;overflow--initial&quot;]/div[@class=&quot;filter-wrapper&quot;]/div[@class=&quot;filter&quot;]/div[@class=&quot;other-filter-wrapper&quot;]/div[@class=&quot;filterType&quot;]/div[@class=&quot;activity&quot;]</value>
      <webElementGuid>574bee34-bdb0-4213-af1b-29e80c050e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='uncontrolled-tab-example-tabpane-grouped']/div/div/div/div/div[3]/div</value>
      <webElementGuid>193e2b85-7be2-4b9e-9116-ef0566169799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::div[8]</value>
      <webElementGuid>1d7e5a9d-1204-4820-9296-f50a281b50db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/following::div[11]</value>
      <webElementGuid>742bbf01-5fc8-4a2d-99f1-2f0eb5b70fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/preceding::div[5]</value>
      <webElementGuid>da695ede-d56e-4ab1-a6b0-af00405861d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/preceding::div[9]</value>
      <webElementGuid>96316bc6-735c-4523-9564-181bb6977621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Service']/parent::*</value>
      <webElementGuid>dd85ccaa-0c52-4b13-a949-f9dc4d67b153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div</value>
      <webElementGuid>2315dfc0-0298-4d3a-abca-a213e975f66f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Service' or . = 'Service')]</value>
      <webElementGuid>9e72e617-eec9-4e0e-8e0c-30acf695775c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
