<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add, Edit or Delete Contacts</name>
   <tag></tag>
   <elementGuidId>edcf9d43-2519-4ef7-9320-81bc413e295b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/section/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Add, Edit or Delete Contacts&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fd2c5186-78ed-4e3d-893e-c33d6f8ce923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>eb6376a2-f10e-4eaa-8bab-53c92e1d3961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add, Edit or Delete Contacts</value>
      <webElementGuid>876a2165-ea12-47a5-8be3-39b5e9659100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-JrDLc knFozZ&quot;]/main[1]/section[@class=&quot;dashboard__container scrollbar&quot;]/div[@class=&quot;contact-wrapper&quot;]/div[@class=&quot;heading&quot;]/div[@class=&quot;title&quot;]</value>
      <webElementGuid>f838afef-5801-49fc-b18a-dd9089858d2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/section/div/div/div</value>
      <webElementGuid>9d3a90ec-c554-4991-a37a-e70a7cc20935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Richard Bayo'])[1]/following::div[3]</value>
      <webElementGuid>debcac43-02d8-418c-bfa5-f65231349849</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Contacts'])[1]/following::div[11]</value>
      <webElementGuid>cf374990-93e4-4461-b9b1-f9dd04c67050</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Grouped Contacts'])[1]/preceding::div[1]</value>
      <webElementGuid>7f7cf40e-4e7c-4354-97ad-c6832200d422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter'])[1]/preceding::div[3]</value>
      <webElementGuid>e533a6c1-54a3-4200-8e66-f89df4aac777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add, Edit or Delete Contacts']/parent::*</value>
      <webElementGuid>1a7f0699-a107-455e-878e-0c44d6f7cdc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>3fb5bf4d-3dfd-4a63-bfed-dbca62381552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Add, Edit or Delete Contacts' or . = 'Add, Edit or Delete Contacts')]</value>
      <webElementGuid>76f54e79-1dbb-429f-9e1d-70d135457b34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
