<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_customers0.amount must be greater than _a3a71f</name>
   <tag></tag>
   <elementGuidId>4ca80dd0-b059-4030-b23c-22ea4cadb353</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.go1415219401</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f73b31b2-a622-4acc-8031-70e1d2d2bd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>cb98df8d-51ab-4def-a59b-e43ac7ba82f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>9ff0edf5-1acd-4a3f-b1a3-a3a0c305e2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go1415219401</value>
      <webElementGuid>b1ac7eb1-b31b-49cc-8e23-1ba3fd4fcb66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&quot;customers[0].amount&quot; must be greater than or equal to 100</value>
      <webElementGuid>25c4e155-0802-4548-befe-8eb84bd9a76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;go2294718771&quot;]/div[@class=&quot;go1415219401&quot;]</value>
      <webElementGuid>a652f2d6-fdf0-4766-8a5d-97f1ce8421c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]</value>
      <webElementGuid>a1751db1-6679-4f95-b07d-c40dd1e5de7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fund Wallet'])[1]/preceding::div[8]</value>
      <webElementGuid>54f6779e-2b43-43e8-a5c8-e09dc4f7b3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction History'])[1]/preceding::div[8]</value>
      <webElementGuid>3ef5f42f-6367-4cb0-82a1-58ff476da010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='&quot;customers[0].amount&quot; must be greater than or equal to 100']/parent::*</value>
      <webElementGuid>2caeb2cf-0e22-438c-ac2a-3d16917def2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]</value>
      <webElementGuid>36051a34-9101-46b9-b261-f1c6b821eb4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '&quot;customers[0].amount&quot; must be greater than or equal to 100' or . = '&quot;customers[0].amount&quot; must be greater than or equal to 100')]</value>
      <webElementGuid>06a6ce6f-5a2a-4a75-aca5-151ae6aade1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
