<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_country</name>
   <tag></tag>
   <elementGuidId>7e83bb77-9b4d-48de-b438-3174e572aaf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#demo-simple-select-outlined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='demo-simple-select-outlined']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8eee2597-de15-4466-b0e6-3d362cd18231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiSelect-outlined MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>79068815-63a6-42a0-ab47-ffb081a66f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>10fa9bbf-aafa-4510-bbab-97eba6a87d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>88630a3f-74b1-48aa-81e8-e559e4d2bcd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>5fbe3b98-8c32-44a3-8a8b-f8daf9e7e955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>demo-simple-select-outlined-label demo-simple-select-outlined</value>
      <webElementGuid>28e1e3c5-4126-4736-9f5e-ce46dacd0454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo-simple-select-outlined</value>
      <webElementGuid>de06b935-4eb8-4d1d-ae4b-297759fee657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>​</value>
      <webElementGuid>bfe963b7-e771-4ed8-95d8-6f5206329745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;demo-simple-select-outlined&quot;)</value>
      <webElementGuid>ca923612-6b40-4cd0-98da-01f36b6a5966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='demo-simple-select-outlined']</value>
      <webElementGuid>eaa26317-c70e-4e4e-8f99-835cb804e048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country'])[1]/following::div[2]</value>
      <webElementGuid>fec225a0-c724-47ef-ab02-a1a9c8070e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sender ID'])[4]/following::div[6]</value>
      <webElementGuid>7770c099-e6b8-4a48-b717-d449bfad9cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Country'])[2]/preceding::div[1]</value>
      <webElementGuid>c6e77700-16c2-4ce1-bd6b-e847a390c4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div</value>
      <webElementGuid>f39244be-bbd8-40fb-9254-c1fcccd5ff7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'demo-simple-select-outlined' and (text() = '​' or . = '​')]</value>
      <webElementGuid>ba21242b-4297-4806-be32-9cb7f52c171d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
