<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_10.00_sc-dLMFU bKPCnw otpInput</name>
   <tag></tag>
   <elementGuidId>fbbd19f0-25b1-461f-a7de-9b44563ce8f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.sc-dLMFU.bKPCnw.otpInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc649b4a-9325-491f-ad0d-1e3dbf3c2d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>62px</value>
      <webElementGuid>71d151bc-0163-407f-bd2a-ba1284a898bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>45px</value>
      <webElementGuid>ce614fe0-654b-47f7-86f1-fa920d774e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ebb3b5f-1efd-4209-93ef-03ed635a8ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-dLMFU bKPCnw otpInput</value>
      <webElementGuid>42c38822-152e-4d7a-9fe2-decf8889b2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b40e2a79-e13d-497c-8a13-4cd71314a642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;fade modal show&quot;]/div[@class=&quot;modal-dialog modal-md modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;sc-ikkxIA bmfCoU&quot;]/div[@class=&quot;otpContainer mb-5&quot;]/div[@class=&quot;sc-eldPxv iYAhZo&quot;]/div[@class=&quot;sc-eDPEul bnqcXw otpInput&quot;]/input[@class=&quot;sc-dLMFU bKPCnw otpInput&quot;]</value>
      <webElementGuid>85ecf2c3-c97b-4a84-bc2c-113270c074a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='5']</value>
      <webElementGuid>a1a55e94-b891-4f53-b8cc-b4e7cf58d532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>5b346a6c-d208-4ca0-b5c4-2fade9f32564</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>5d097c48-b8c4-4d76-afec-bc12b21e2be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
