<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Airtime</name>
   <tag></tag>
   <elementGuidId>ec92d2b8-f111-4784-8f1c-8d85edcfa2cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showSideMenu']/nav/ul[3]/ul/li/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.side-navigation-panel-select-inner-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3baaf80a-f7ff-4582-bd4a-f9d5fa309523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-navigation-panel-select-inner-option-text</value>
      <webElementGuid>875a3756-8ac0-4d79-856a-0a0991b0c449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Airtime</value>
      <webElementGuid>08cff9af-eeda-42ea-8d5b-534e1736e9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSideMenu&quot;)/nav[@class=&quot;side-navigation-panel&quot;]/ul[@class=&quot;side-navigation-panel-select&quot;]/ul[@class=&quot;side-navigation-panel-select-inner&quot;]/li[@class=&quot;side-navigation-panel-select-inner-wrap&quot;]/div[@class=&quot;side-navigation-panel-select-inner-option&quot;]/span[@class=&quot;side-navigation-panel-select-inner-option-wrap&quot;]/span[@class=&quot;side-navigation-panel-select-inner-option-text&quot;]</value>
      <webElementGuid>5b4fdffe-04fb-4783-9ca9-d5a2a8f85d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSideMenu']/nav/ul[3]/ul/li/div/span/span</value>
      <webElementGuid>bc2b96a0-f396-464e-ba2b-9fe16b3e09b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/following::span[2]</value>
      <webElementGuid>2737d874-f371-4648-87fa-3d4a28771bc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk Service'])[1]/following::span[4]</value>
      <webElementGuid>65b6eaeb-9695-46d8-ace6-34044e34c139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/preceding::span[1]</value>
      <webElementGuid>c240dd39-ceb7-4eff-8ae5-907ed6a90093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayBills'])[1]/preceding::span[3]</value>
      <webElementGuid>b1baa342-1939-4752-9aa3-7b3acac2f356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Airtime']/parent::*</value>
      <webElementGuid>6c32cb9e-63e7-4c44-96d4-09e682713a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[3]/ul/li/div/span/span</value>
      <webElementGuid>ca929a23-3ba3-4d2d-9a48-c83f2e82c7ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Airtime' or . = 'Airtime')]</value>
      <webElementGuid>391f7897-a8b5-4749-af4a-b4294d4874c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
