<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_SMS</name>
   <tag></tag>
   <elementGuidId>c5410e35-ddd2-4826-a3c1-3bca38cf3d5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='showSideMenu']/nav/ul[3]/ul/li[4]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;side-navigation&quot;i >> internal:text=&quot;SMS&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7319bdc3-41f5-4a48-a938-4d85d3aa3ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>side-navigation-panel-select-inner-option-text</value>
      <webElementGuid>870d7221-7ab5-4b20-9e9a-e40e5651f130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMS</value>
      <webElementGuid>77fe27f7-dbb1-4474-8539-9b849ada5db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;showSideMenu&quot;)/nav[@class=&quot;side-navigation-panel&quot;]/ul[@class=&quot;side-navigation-panel-select&quot;]/ul[@class=&quot;side-navigation-panel-select-inner&quot;]/li[@class=&quot;side-navigation-panel-select-inner-wrap&quot;]/div[@class=&quot;side-navigation-panel-select-inner-option&quot;]/span[@class=&quot;side-navigation-panel-select-inner-option-wrap&quot;]/span[@class=&quot;side-navigation-panel-select-inner-option-text&quot;]</value>
      <webElementGuid>264426a9-2236-4164-ab5c-5f373bbbb335</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showSideMenu']/nav/ul[3]/ul/li[4]/div/span/span</value>
      <webElementGuid>33cab948-de86-489d-bf3c-8bd1682fa879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PayBills'])[1]/following::span[2]</value>
      <webElementGuid>646324de-5be5-4e68-b173-25cdb57aff56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data'])[1]/following::span[4]</value>
      <webElementGuid>77f55205-146e-4dcd-9cdf-c9c1e12ad8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contacts'])[1]/preceding::span[1]</value>
      <webElementGuid>99bc8bb3-aa5b-454a-9489-fef12b6587b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prices'])[1]/preceding::span[3]</value>
      <webElementGuid>8adee5c8-0d30-49c9-bac5-4008d2390a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SMS']/parent::*</value>
      <webElementGuid>7450cec8-8788-4ebf-903a-b71927ff6573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/span/span</value>
      <webElementGuid>e930acab-b09d-4618-827d-84c4d5b32ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'SMS' or . = 'SMS')]</value>
      <webElementGuid>f86ec292-85bf-4a51-afb5-8900054ee191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
