<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ungrouped_apply_btn</name>
   <tag></tag>
   <elementGuidId>3befc6d1-0f0f-4658-b4f6-f5afd41f1364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//div//button[@type='button'][normalize-space()='Apply'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
